### ISSUE TITLE
when hashed, cashed: (hash) true – contract errors not displayed 

### ISSUE THREAD

**Issue by alist** [eris-ltd/eris-compilers#34]
on lllc-server version 0.9.0

When there are solidarity contract errors, calling compile on a cached results prints empty bytecode: and abi: lines.

```lllc-server compile contracts/property.sol```

Trivially modifying whitespace is a workaround to get the error to re-print.

**Comment by ebuchman** [comment]
we should add a `no-cache` flag. you can also blow away the cache. its in `~/.eris/scratch/lllc`

**Comment by alist** [comment]
Is this expected behavior?

**Comment by ebuchman** [comment]
no i don't think so.

**Comment by compleatang** [comment]
closing this issue. should be solveable via messing with the languages config.
