### ISSUE TITLE
command line call to /usr/bin/solc only works with single contract .sol files (eris-compilers/compile.go)

### ISSUE THREAD

**Issue by ratranqu** [eris-ltd/eris-compilers#47]
Currently, requesting a compilation on a .sol contract (`eris-compilers compile --local original.sol`), results in the following command line being called (it's the same problem for the binary and the abi file):
`/usr/bin/solc --bin [original_hash.sol] [import1_hash.sol, import2_hash.sol] | grep Binary A1| tail -n 1`

This is the result of what is defined in `~/.eris/languages/config.json` (and possibly also that is in `eris-compilers/compile.go`).

When the the `original.sol` file only contains one contract, with no imports, this is fine.

However, it breaks when there is more than one contract definition in the `original.sol` file or when there is one or more import containing a contract definition, only the last contract (ordered alphabetically its seems) compiled by `/usr/bin/solc` will be processed properly (and thus only binary deployed to the chain and abi written to the `./abi` directory).

This is because the format of the result of `/usr/bin/solc [--bin|--abi] file1 file2 file2` returns all Binaries/abis one after the others, hence the `tail -n 1` chops off all but the last contract returned.

a simple demonstration of the problem can be seen with the following set of .sol files:

a.sol:
```
contract a {
  address owner;

  function a() {
    owner = msg.sender;
  }
}
```
b.sol:
```
import "a.sol";

contract b is a {
  uint value;

  function set(uint v) {
    value = v;
  }
}


contract c {
  uint value;

  fnction set(uint v) {
    value = v;
  }
}
```

Compiling the abi (for ease of output, using the `--bin` flag has the same impact) b.sol through: ` solc --abi b.sol` gives:
```
======= a =======
Contract JSON ABI
[{"inputs":[],"type":"constructor"}]


======= b =======
Contract JSON ABI
[{"constant":false,"inputs":[{"name":"v","type":"uint256"}],"name":"set","outputs":[],"type":"function"}]


======= c =======
Contract JSON ABI
[{"constant":false,"inputs":[{"name":"v","type":"uint256"}],"name":"set","outputs":[],"type":"function"}]

```

So problem #1 is that the `tail -n 1` truncates all but the last contract.

Furthermore, it seems that `eris-compilers compile b.sol` preprocesses the `b.sol` file upfront,  providing a hash for the original file (`b.sol` in our case) and for each imported files (`a.sol` in this case). This means that when there is more than one contract in the main file (as in `b.sol`), then there will be a single hash value allocated to `b.sol`, for both the `b` and the `c` contracts in `b.sol`. I suspect this is not desirable (as then you lose access to one of the two contracts). The same behaviour is likely happening when there are more than one contract in an imported file.

So problem #2 is that the preprocessing of the files to be compiled is such that there is an assumption that there is a single contract per file. This may be a valid assumption, and if so, it would be good to prevent compilation to go ahead when there are more than one contracts in an original file or in an imported file.

A suggestion to fix this is to use the `--output $dir` flag from `solc`. It means that eris-compilers doesn't need to focus on identifying the different contracts present in the original file or the import files (which I think is good, as you reuse the feature directly from `solc`). 

However, it means that the logic to assign the hash and deploy needs to change.

I would like to hear/read people's views on this so I can take a stab at fixing it.

**Comment by compleatang** [comment]
Instead of hashing a single file perhaps we should be thinking in terms of directories. We can hash the directory and then use that directory rather than single files. The compilers service has needed some work for a few months so thanks for prodding us here as the time is nigh to improve this now. 

If you wanted to look at making that change that would be super helpful! I can make sure that things are sorted from the eris-pm side for coherence. If you are otherwise occupied I can try to get to this change sometime during the week upcoming.

**Comment by ratranqu** [comment]
Casey,

I'll take care of it over the course of next week.

In terms of the hashing done at directory level (or file level, as currently done), I would say it's tied to where we want the lowest unit of code to be.

What is the view to do it at contract level? Solc returns the byte code and the abi at contract level.

So chop up the file + all associated imports as a collection of contracts and assign a hash to the contract.

Gut feel I tend to prefer smaller units (increases reuse), but haven't thought it through much.

Alex

Sent from my iPhone

On 6 Feb 2016, at 11:34, Casey Kuhlman <notifications@github.com<mailto:notifications@github.com>> wrote:


Instead of hashing a single file perhaps we should be thinking in terms of directories. We can hash the directory and then use that directory rather than single files. The compilers service has needed some work for a few months so thanks for prodding us here as the time is nigh to improve this now.

If you wanted to look at making that change that would be super helpful! I can make sure that things are sorted from the eris-pm side for coherence. If you are otherwise occupied I can try to get to this change sometime during the week upcoming.

-

**Comment by compleatang** [comment]
Smaller units probably better indeed. 

May be easiest to have a separate pathway for directory based compilation. EPM will know for example if a `deploy` job references a file or a directory and can send the file or directory to the proper endpoint here. That would then give users the choice. 

This still could be a bit limiting in complex contracts scenarios [like Andreas mentions here](https://docs.erisindustries.com/tutorials/solidity/solidity-6/), but we can deal with that later.

**Comment by compleatang** [comment]
This is now sorted. Thanks Alex!
