### ISSUE TITLE
Unable to deploy contracts using compilers downloaded locally / offline

### ISSUE THREAD

**Issue by yogaa** [eris-ltd/eris-compilers#70]
Hi All,

 We are trying to deploy the contracts using the local compilers, please find the series of our commands below to achieve the same : 
1. `eris services start compilers `
2. `eris pkgs do --chain simplechain --address $addr --compiler 192.168.99.101:9091`

(also we have updated our compilers using `eris services update compiler` command)

![local-complier-error1](https://cloud.githubusercontent.com/assets/20512484/16950652/fc57c40a-4dde-11e6-8410-af07e224906d.png)

The same command would get executed using the online compilers when we would run `eris pkgs do --chain simplechain --address $addr` ( please see the screen shot given below)

![local-complier-error2](https://cloud.githubusercontent.com/assets/20512484/16950799/a7fad202-4ddf-11e6-9b8f-64ec25337076.png)

Any help would be really helpful if we can use the Eris compilers locally as we want our application to run within the corporate walls.

**Comment by VoR0220** [comment]
If you have the compiler installed locally and are running eris version 0.12.0-rc2, simply run the command 

```eris pkgs do --chain simplechain --address $addr --compiler ""``` and that should work. Let me know if it doesn't.

**Comment by yogaa** [comment]
I will try doing the above mention workaround in sometime thanks for the immediate reply.

dont mind my curiosity but cant we run on the same command on eris version : 0.11  ??

**Comment by VoR0220** [comment]
@yogaa I don't believe you can...I only recently added specifications to enable local compiler running directly from CLI...there might have been a workaround of some kind, but I'm unaware of it.

**Comment by yogaa** [comment]
i wasnt able to find eris version 0.12.0-rc2, i am using _0.12.0_ and i tried cleaning up everything but no luck, any other alternative(s) would be helpful.

thnx

**Comment by compleatang** [comment]
@yogaa just to be clear what Docker version and Eris version do you currently have installed?

**Comment by yogaa** [comment]
$ docker version

Client:
 Version:      1.11.2
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   b9f10c9
 Built:        Wed Jun  1 21:20:08 2016
 OS/Arch:      windows/amd64

Server:
 Version:      1.11.2
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   b9f10c9
 Built:        Wed Jun  1 21:20:08 2016
 OS/Arch:      linux/amd64

**********************************************************************

$ eris version
Eris CLI Version: 0.11.4

**Comment by compleatang** [comment]
Thanks. So there is no reason that this won't work on 0.11.4. Use this sequence.

Edit the file: ~/.eris/services/compilers.toml to use the `quay.io/eris/compilers:0.11.4` image instead of the `quay.io/eris/compilers` image. 

Then:

```
docker pull quay.io/eris/compilers:0.11.4
eris services start compilers
comp_ip=$(docker-machine ip eris)
eris pkgs do --chain simplechain --address $addr --compiler http://$comp_ip:9091
```

That should set you up.

**Comment by yogaa** [comment]
thanks Casey , we had got stuck past couple of days thanks the solution it has worked.

when we change the eris version then should we edit the _~/.eris/services/compilers.toml_ file `quay.io/eris/compilers: <ver. no>' and perform the respective steps as mentioned

**Comment by compleatang** [comment]
yes. that would be the way forward for a continual local compilers solution. We will make this easier as more folks are behind firewalls or otherwise wanting a local compilers service. Can we close this issue?

**Comment by yogaa** [comment]
Yes surely u may close the issue. Thanks a lot for timely and quick responses on the issue :+1:
