### ISSUE TITLE
eris packages doesnt create abi, cannot deploy smart contract

### ISSUE THREAD

**Issue by infinius12345** [eris-ltd/eris-compilers#74]
{docker version
Client:
 Version:      1.11.2
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   b9f10c9
 Built:        Wed Jun  1 21:47:50 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.11.2
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   b9f10c9
 Built:        Wed Jun  1 21:47:50 2016
 OS/Arch:      linux/amd64}

{eris version
Eris CLI Version: 0.12.0}

.{go version
go version go1.2.1 linux/amd64}

using Ubuntu 14.04- Trusty Tahr LTS on Virtual Box

**i expected to create an epm.json while following the tutorial but i am stuck with the erro that abi doesnt exist, using a local compiler and i understand that this is a similiar issue as https://github.com/eris-ltd/eris-cli/issues/813**
**so i already tried the steps provided**
cat ~/.eris/services/compilers.toml

name           = "compilers"
description = """
Eris' LLLC (Lovely Little Language Compile) Server.

This eris service compiles smart contract languages.
"""

status = "beta"

[service]
image          = "quay.io/eris/compilers:0.12.0"
data_container = true
ports          = [ "9090:9098", "9091:9099" ]
volumes        = [  ]
environment    = [ "SECURE_PORT=9098", "UNSECURE_PORT=9099" ]

[maintainer]
name = "Eris Industries"
email = "support@erisindustries.com"

[location]
dockerfile = "https://github.com/eris-ltd/common/blob/master/docker/compilers/Dockerfile"
repository = "https://github.com/eris-ltd/eris-compilers"
website = ""

docker pull quay.io/eris/compilers:0.12.0
eris services start compilers

---------------------------------------------------------------------------------------------------------------------------
**when i execute the following command-**~/.eris/apps/idi$ eris pkgs do --chain simplechain --address $addr --compiler 172.17.0.1:9091 -d **where the ip is for docker**
eris pkgs do --chain simplechain --address $addr --compiler 172.17.0.1:9091 -d Checking Linux Docker socket                  unix:///var/run/docker.sock
Connecting to Docker                          unix:///var/run/docker.sock
The marmots could not find docker-machine installed. While it is not required to use the Eris platform, we strongly recommend it be installed for maximum blockchain awesomeness.
Welcome! Say the marmots. Running package
                                    host path=/home/mishravi/.eris/apps/idi
                                          pwd=/home/mishravi/.eris/apps/idi
The marmots could not read that package.json. Will use defaults.
Booting chain from chain flag                 simplechain
Starting chain                           name=simplechain
Chain defaults set                      image=quay.io/eris/erisdb:0.12.0
Marshalling chain
                                     autodata=true
Connecting to service                         simplechain
                                internal name=keys
                                         link=true
                                         name=keys
                                         type=service
                                 volumes from=true
Chain definition loaded                   cmd=
                             container number=1
                                   entrypoint=erisdb-wrapper
                                  environment=[]
Booting chain dependencies             chains=[]
                                     services=[keys]
Loading service definition                    keys
Defaulting to service                 service=keys
Starting a chain                              simplechain
                              chain container=simplechain-bf6c7279-3be3-47f3-9ec0-2a132a5d057b
                                  environment=[CHAIN_ID=simplechain]
                              ports published=false
Running container                             simplechain-bf6c7279-3be3-47f3-9ec0-2a132a5d057b
Container already running. Skipping           simplechain-bf6c7279-3be3-47f3-9ec0-2a132a5d057b
Defaulting to service                 service=idi_tmp_
App action built
Getting data container situated           dir=inbound
Loading data definition                       idi_tmp_
Creating data container                       idi_tmp_-a574dd5b-dde0-4617-92a4-20a8b4ab8484
Data container created                        idi_tmp_-a574dd5b-dde0-4617-92a4-20a8b4ab8484
Setting app data for container           dest=/home/eris/.eris/apps/idi
                                       source=/home/mishravi/.eris/apps/idi
Importing                                from=/home/mishravi/.eris/apps/idi
                                           to=/home/eris/.eris/apps/idi
Giving myself all the names                   idi_tmp_
Using names                    data container=idi_tmp_-a574dd5b-dde0-4617-92a4-20a8b4ab8484
                            service container=idi_tmp_-a574dd5b-dde0-4617-92a4-20a8b4ab8484
Executing data container                      
Loading data definition                       idi_tmp_
Executing data container                      idi_tmp_-a574dd5b-dde0-4617-92a4-20a8b4ab8484
                                         args=[test -d /home/eris/.eris/apps/idi]
Data container configured                 cmd=[test -d /home/eris/.eris/apps/idi]
                                   entrypoint=[]
Data container configured               image=quay.io/eris/data:0.12.0
Executing interactive data container          interactive-8eb98025-71fa-4686-a51c-99a1457f23ac
Waiting for container to exit                 interactive-8eb98025-71fa-4686-a51c-99a1457f23ac
Removing data container                       interactive-8eb98025-71fa-4686-a51c-99a1457f23ac
Data container removed                        interactive-8eb98025-71fa-4686-a51c-99a1457f23ac
Running data container                        idi_tmp_-a574dd5b-dde0-4617-92a4-20a8b4ab8484
                                         args=[mkdir -p /home/eris/.eris/apps/idi]
Data container configured                 cmd=[mkdir -p /home/eris/.eris/apps/idi]
                                   entrypoint=[]
Data container configured               image=quay.io/eris/data:0.12.0
Starting data container                       interactive-578ccbbd-3cbc-4fa7-8fea-1d0fbbecd066
Waiting for data container to exit            interactive-578ccbbd-3cbc-4fa7-8fea-1d0fbbecd066
Getting logs from container                   interactive-578ccbbd-3cbc-4fa7-8fea-1d0fbbecd066
Removing data container                       interactive-578ccbbd-3cbc-4fa7-8fea-1d0fbbecd066
Container removed                             interactive-578ccbbd-3cbc-4fa7-8fea-1d0fbbecd066
Importing                                from=/home/mishravi/.eris/apps/idi
                                           to=/home/eris/.eris/apps/idi
Giving myself all the names                   idi_tmp_
Using names                    data container=idi_tmp_-a574dd5b-dde0-4617-92a4-20a8b4ab8484
                            service container=idi_tmp_-a574dd5b-dde0-4617-92a4-20a8b4ab8484
Executing data container                      
Loading data definition                       idi_tmp_
Executing data container                      idi_tmp_-a574dd5b-dde0-4617-92a4-20a8b4ab8484
                                         args=[test -d /home/eris/.eris/apps/idi]
Data container configured                 cmd=[test -d /home/eris/.eris/apps/idi]
                                   entrypoint=[]
Data container configured               image=quay.io/eris/data:0.12.0
Executing interactive data container          interactive-a8218a62-3b6f-4a49-b133-952940b70286
Waiting for container to exit                 interactive-a8218a62-3b6f-4a49-b133-952940b70286
Removing data container                       interactive-a8218a62-3b6f-4a49-b133-952940b70286
Data container removed                        interactive-a8218a62-3b6f-4a49-b133-952940b70286
Copying into container                        idi_tmp_-a574dd5b-dde0-4617-92a4-20a8b4ab8484
                                         path=/home/mishravi/.eris/apps/idi
Running data container                        idi_tmp_-a574dd5b-dde0-4617-92a4-20a8b4ab8484
                                         args=[chown --recursive eris /home/eris/.eris/apps/idi]
Data container configured                 cmd=[chown --recursive eris /home/eris/.eris/apps/idi]
                                   entrypoint=[]
Data container configured               image=quay.io/eris/data:0.12.0
Starting data container                       interactive-c071fe0e-161d-4223-9c73-69e5e12405c4
Waiting for data container to exit            interactive-c071fe0e-161d-4223-9c73-69e5e12405c4
Getting logs from container                   interactive-c071fe0e-161d-4223-9c73-69e5e12405c4
Removing data container                       interactive-c071fe0e-161d-4223-9c73-69e5e12405c4
Container removed                             interactive-c071fe0e-161d-4223-9c73-69e5e12405c4
Package path does not exist on the host or is inside the pkg path
ABI path does not exist on the host or is inside the pkg path
EPM files do not exist on the host or are inside the pkg path
Performing action. This can sometimes take a wee while
                                        image=quay.io/eris/epm:0.12.0
                                      service=idi_tmp_
                                   entrypoint=epm --chain chain:46657 --sign keys:4767 --debug  --overwrite  --output json --summary  --gas 1111111111 --compiler 172.17.0.1:9091 --address 1475A062AE126DE72CFDE6B8CD6BE525EFC2340F --fee 1234 --amount 9999
                                      workdir=/home/eris/.eris/apps/idi
Executing container                           idi_tmp_-83f014e5-4d3e-4ae6-a1fa-33eb56b09060
Manage data containers?              autodata=true
Data container already exists, am not creating
Container does not exist. Creating      image=quay.io/eris/epm:0.12.0
Executing interactive container               interactive-70a19f01-8496-46b8-983a-5c085c11b8d6
                                          cmd=[]
                               data container=idi_tmp_-a574dd5b-dde0-4617-92a4-20a8b4ab8484
                                   entrypoint=[epm --chain chain:46657 --sign keys:4767 --debug --overwrite --output json --summary --gas 1111111111 --compiler 172.17.0.1:9091 --address 1475A062AE126DE72CFDE6B8CD6BE525EFC2340F --fee 1234 --amount 9999]
                                  environment=[]
                                        image=quay.io/eris/epm:0.12.0
                              ports published=false
                                         user=eris
                                         vols=[]
                                      workdir=/home/eris/.eris/apps/idi
Waiting for container to exit                 interactive-70a19f01-8496-46b8-983a-5c085c11b8d6
Removing container                            interactive-70a19f01-8496-46b8-983a-5c085c11b8d6
Container removed                             interactive-70a19f01-8496-46b8-983a-5c085c11b8d6
Hello! I'm EPM.
Using Compiler at                             http://172.17.0.1:9091
Using Chain at                                http://chain:46657/
With ChainID                                  
Using Signer at                               http://keys:4767
Using ChainID from Node                       simplechain
Loading eris-pm Package Definition File.
Loading eris-pm file                     name=epm
                                         path=/home/eris/.eris/apps/idi
Executing Job                                 defaultAddr
Type                                          Account
Setting Account                               1475A062AE126DE72CFDE6B8CD6BE525EFC2340F
Getting Public Key                       from=http://keys:4767
Executing Job                                 setStorageBase
Type                                          Set
Setting Variable                              5
Executing Job                                 deployStorageK
Type                                          Deploy
Contract path                                 idi.sol
Setting compiler path                         http://172.17.0.1:9091
Language to use                               sol
File to compile                       cached?=false
                                         hash=14cecb1ec3466bc52b70c6291885a66e55b592fc3be7195ca2fe80e41c701211
Compiling code remotely                   url=http://172.17.0.1:9091/compile
Deploying a single contract             contr=idi
Executing Job                                 setStorage
Type                                          Call
Replacement Match Found                 match=$deployStorageK
Fixing Variables =>                       res=
                                          var=deployStorageK
ABI Error                                 abi=
                                         data=
                                         dest=
                                       rawErr=Abi doesn't exist for =>	abi

There has been an error in finding or in using your ABI. ABI's are "Application Binary
Interface" and they are what let us know how to talk to smart contracts.

These little json files can be read by a variety of things which need to talk to smart
contracts so they are quite necessary to be able to find and use properly.

The ABIs are saved after the deploy events. So if there was a glitch in the matrix,
we apologize in advance.

The marmot recovery checklist is...
  * ensure your chain is running and you have enough validators online
  * ensure that your contracts successfully deployed
  * if you used imports or have multiple contracts in one file check the instance
    variable in the deploy and the abi variable in the call/query-contract
  * make sure you're calling or querying the right function
  * make sure you're using the correct variables for job results

Cleaning up
No throwaway chain to destroy
Getting data container situated           dir=outbound
Loading data definition                       idi_tmp_
Setting app data for container           dest=/home/mishravi/.eris/apps
                                       source=/home/eris/.eris/apps/idi
Exporting data container                      idi_tmp_
Giving myself all the names                   idi_tmp_
Using names                    data container=idi_tmp_-a574dd5b-dde0-4617-92a4-20a8b4ab8484
                            service container=idi_tmp_-a574dd5b-dde0-4617-92a4-20a8b4ab8484
Untarring package from container              /tmp/idi_tmp_472225569
Copying out of container                      idi_tmp_-a574dd5b-dde0-4617-92a4-20a8b4ab8484
                                         path=/home/eris/.eris/apps/idi
Move all files/dirs out of a dir and `rm -rf` that dir
                                         from=/tmp/idi_tmp_472225569/.eris
                                           to=/tmp/idi_tmp_472225569
No files to move
Removing directory                            /tmp/idi_tmp_472225569/.eris
Move all files/dirs out of a dir and `rm -rf` that dir
                                         from=/tmp/idi_tmp_472225569
                                           to=/home/mishravi/.eris/apps
Removing directory                            /tmp/idi_tmp_472225569
Package path does not exist on the host or is inside the pkg path
ABI path does not exist on the host or is inside the pkg path
EPM files do not exist on the host or are inside the pkg path
Removing data container                       idi_tmp_-a574dd5b-dde0-4617-92a4-20a8b4ab8484
Removing container                            idi_tmp_-a574dd5b-dde0-4617-92a4-20a8b4ab8484
Removing data dir on host                 dir=/home/mishravi/.eris/scratch/data/idi_tmp_

-------------------------------------------------------------------------------------------------------------------------

**as you can see the deploy was successful, and from my understanding after a deploy an abi folder is supposed to be generated but** 
~/.eris/apps/idi$ ls
epm.yaml  idi.sol
**this is my output, in the directory it was called from and i have also tried using the abi-path flag but i get the same result.

The problem can be reproduced by following the tutorial, also i read some where that a similiar problem was solved in 0.12.0-rc1 .. how do you i update to rc1, eris update always takes me to master which is 0.12.0**

**Comment by VoR0220** [comment]
You have to update to rc2

**Comment by compleatang** [comment]
In the alternative just add an http:// before your compilers ip address.

**Comment by infinius12345** [comment]
Apologies - i am really new to blockchains/programming, and have tried eris update but it takes me to master brach which is 0.12.0 is there a workaround ?

**Comment by infinius12345** [comment]
**Just Tried http:// same result**
:~/.eris/apps/idi$ eris pkgs do --chain simplechain --address $addr --compiler http://172.17.0.1:9091 -d --abi-path "~/.eris/apps/idi"
Checking Linux Docker socket                  unix:///var/run/docker.sock
Connecting to Docker                          unix:///var/run/docker.sock
The marmots could not find docker-machine installed. While it is not required to use the Eris platform, we strongly recommend it be installed for maximum blockchain awesomeness.
Welcome! Say the marmots. Running package
                                    host path=/home/mishravi/.eris/apps/idi
                                          pwd=/home/mishravi/.eris/apps/idi
The marmots could not read that package.json. Will use defaults.
Booting chain from chain flag                 simplechain
Starting chain                           name=simplechain
Chain defaults set                      image=quay.io/eris/erisdb:0.12.0
Marshalling chain
                                     autodata=true
Connecting to service                         simplechain
                                internal name=keys
                                         link=true
                                         name=keys
                                         type=service
                                 volumes from=true
Chain definition loaded                   cmd=
                             container number=1
                                   entrypoint=erisdb-wrapper
                                  environment=[]
Booting chain dependencies             chains=[]
                                     services=[keys]
Loading service definition                    keys
Defaulting to service                 service=keys
Starting a chain                              simplechain
                              chain container=simplechain-bf6c7279-3be3-47f3-9ec0-2a132a5d057b
                                  environment=[CHAIN_ID=simplechain]
                              ports published=false
Running container                             simplechain-bf6c7279-3be3-47f3-9ec0-2a132a5d057b
Container already running. Skipping           simplechain-bf6c7279-3be3-47f3-9ec0-2a132a5d057b
Defaulting to service                 service=idi_tmp_
App action built
Getting data container situated           dir=inbound
Loading data definition                       idi_tmp_
Creating data container                       idi_tmp_-dee17767-a0c0-4680-a4fd-7a93073f9ff5
Data container created                        idi_tmp_-dee17767-a0c0-4680-a4fd-7a93073f9ff5
Setting app data for container           dest=/home/eris/.eris/apps/idi
                                       source=/home/mishravi/.eris/apps/idi
Importing                                from=/home/mishravi/.eris/apps/idi
                                           to=/home/eris/.eris/apps/idi
Giving myself all the names                   idi_tmp_
Using names                    data container=idi_tmp_-dee17767-a0c0-4680-a4fd-7a93073f9ff5
                            service container=idi_tmp_-dee17767-a0c0-4680-a4fd-7a93073f9ff5
Executing data container                      
Loading data definition                       idi_tmp_
Executing data container                      idi_tmp_-dee17767-a0c0-4680-a4fd-7a93073f9ff5
                                         args=[test -d /home/eris/.eris/apps/idi]
Data container configured                 cmd=[test -d /home/eris/.eris/apps/idi]
                                   entrypoint=[]
Data container configured               image=quay.io/eris/data:0.12.0
Executing interactive data container          interactive-87db9e1f-45b5-41a8-8510-801b2f589e26
Waiting for container to exit                 interactive-87db9e1f-45b5-41a8-8510-801b2f589e26
Removing data container                       interactive-87db9e1f-45b5-41a8-8510-801b2f589e26
Data container removed                        interactive-87db9e1f-45b5-41a8-8510-801b2f589e26
Running data container                        idi_tmp_-dee17767-a0c0-4680-a4fd-7a93073f9ff5
                                         args=[mkdir -p /home/eris/.eris/apps/idi]
Data container configured                 cmd=[mkdir -p /home/eris/.eris/apps/idi]
                                   entrypoint=[]
Data container configured               image=quay.io/eris/data:0.12.0
Starting data container                       interactive-726c2b49-9eae-4238-8d92-a5220f16697e
Waiting for data container to exit            interactive-726c2b49-9eae-4238-8d92-a5220f16697e
Getting logs from container                   interactive-726c2b49-9eae-4238-8d92-a5220f16697e
Removing data container                       interactive-726c2b49-9eae-4238-8d92-a5220f16697e
Container removed                             interactive-726c2b49-9eae-4238-8d92-a5220f16697e
Importing                                from=/home/mishravi/.eris/apps/idi
                                           to=/home/eris/.eris/apps/idi
Giving myself all the names                   idi_tmp_
Using names                    data container=idi_tmp_-dee17767-a0c0-4680-a4fd-7a93073f9ff5
                            service container=idi_tmp_-dee17767-a0c0-4680-a4fd-7a93073f9ff5
Executing data container                      
Loading data definition                       idi_tmp_
Executing data container                      idi_tmp_-dee17767-a0c0-4680-a4fd-7a93073f9ff5
                                         args=[test -d /home/eris/.eris/apps/idi]
Data container configured                 cmd=[test -d /home/eris/.eris/apps/idi]
                                   entrypoint=[]
Data container configured               image=quay.io/eris/data:0.12.0
Executing interactive data container          interactive-292bb1f7-c8e8-4a7a-80b2-ecee89188bf2
Waiting for container to exit                 interactive-292bb1f7-c8e8-4a7a-80b2-ecee89188bf2
Removing data container                       interactive-292bb1f7-c8e8-4a7a-80b2-ecee89188bf2
Data container removed                        interactive-292bb1f7-c8e8-4a7a-80b2-ecee89188bf2
Copying into container                        idi_tmp_-dee17767-a0c0-4680-a4fd-7a93073f9ff5
                                         path=/home/mishravi/.eris/apps/idi
Running data container                        idi_tmp_-dee17767-a0c0-4680-a4fd-7a93073f9ff5
                                         args=[chown --recursive eris /home/eris/.eris/apps/idi]
Data container configured                 cmd=[chown --recursive eris /home/eris/.eris/apps/idi]
                                   entrypoint=[]
Data container configured               image=quay.io/eris/data:0.12.0
Starting data container                       interactive-19b1867b-72d4-4b7c-8147-c138b9f5fdc7
Waiting for data container to exit            interactive-19b1867b-72d4-4b7c-8147-c138b9f5fdc7
Getting logs from container                   interactive-19b1867b-72d4-4b7c-8147-c138b9f5fdc7
Removing data container                       interactive-19b1867b-72d4-4b7c-8147-c138b9f5fdc7
Container removed                             interactive-19b1867b-72d4-4b7c-8147-c138b9f5fdc7
Package path does not exist on the host or is inside the pkg path
ABI path does not exist on the host or is inside the pkg path
EPM files do not exist on the host or are inside the pkg path
Performing action. This can sometimes take a wee while
                                        image=quay.io/eris/epm:0.12.0
                                      service=idi_tmp_
                                   entrypoint=epm --chain chain:46657 --sign keys:4767 --debug  --overwrite  --output json --summary  --gas 1111111111 --compiler http://172.17.0.1:9091 --address 1475A062AE126DE72CFDE6B8CD6BE525EFC2340F --fee 1234 --amount 9999
                                      workdir=/home/eris/.eris/apps/idi
Executing container                           idi_tmp_-550aa8a0-fa28-43ec-95af-5575ae4478c1
Manage data containers?              autodata=true
Data container already exists, am not creating
Container does not exist. Creating      image=quay.io/eris/epm:0.12.0
Executing interactive container               interactive-88bb1cd4-02ce-4382-b430-9e583becf254
                                          cmd=[]
                               data container=idi_tmp_-dee17767-a0c0-4680-a4fd-7a93073f9ff5
                                   entrypoint=[epm --chain chain:46657 --sign keys:4767 --debug --overwrite --output json --summary --gas 1111111111 --compiler http://172.17.0.1:9091 --address 1475A062AE126DE72CFDE6B8CD6BE525EFC2340F --fee 1234 --amount 9999]
                                  environment=[]
                                        image=quay.io/eris/epm:0.12.0
                              ports published=false
                                         user=eris
                                         vols=[]
                                      workdir=/home/eris/.eris/apps/idi
Waiting for container to exit                 interactive-88bb1cd4-02ce-4382-b430-9e583becf254
Removing container                            interactive-88bb1cd4-02ce-4382-b430-9e583becf254
Container removed                             interactive-88bb1cd4-02ce-4382-b430-9e583becf254
Hello! I'm EPM.
Using Compiler at                             http://172.17.0.1:9091
Using Chain at                                http://chain:46657/
With ChainID                                  
Using Signer at                               http://keys:4767
Using ChainID from Node                       simplechain
Loading eris-pm Package Definition File.
Loading eris-pm file                     name=epm
                                         path=/home/eris/.eris/apps/idi
Executing Job                                 defaultAddr
Type                                          Account
Setting Account                               1475A062AE126DE72CFDE6B8CD6BE525EFC2340F
Getting Public Key                       from=http://keys:4767
Executing Job                                 setStorageBase
Type                                          Set
Setting Variable                              5
Executing Job                                 deployStorageK
Type                                          Deploy
Contract path                                 idi.sol
Setting compiler path                         http://172.17.0.1:9091
Language to use                               sol
File to compile                       cached?=false
                                         hash=14cecb1ec3466bc52b70c6291885a66e55b592fc3be7195ca2fe80e41c701211
Compiling code remotely                   url=http://172.17.0.1:9091/compile
Deploying a single contract             contr=idi
Executing Job                                 setStorage
Type                                          Call
Replacement Match Found                 match=$deployStorageK
Fixing Variables =>                       res=
                                          var=deployStorageK
ABI Error                                 abi=
                                         data=
                                         dest=
                                       rawErr=Abi doesn't exist for =>	abi

There has been an error in finding or in using your ABI. ABI's are "Application Binary
Interface" and they are what let us know how to talk to smart contracts.

These little json files can be read by a variety of things which need to talk to smart
contracts so they are quite necessary to be able to find and use properly.

The ABIs are saved after the deploy events. So if there was a glitch in the matrix,
we apologize in advance.

The marmot recovery checklist is...
  * ensure your chain is running and you have enough validators online
  * ensure that your contracts successfully deployed
  * if you used imports or have multiple contracts in one file check the instance
    variable in the deploy and the abi variable in the call/query-contract
  * make sure you're calling or querying the right function
  * make sure you're using the correct variables for job results


Cleaning up
No throwaway chain to destroy
Getting data container situated           dir=outbound
Loading data definition                       idi_tmp_
Setting app data for container           dest=/home/mishravi/.eris/apps
                                       source=/home/eris/.eris/apps/idi
Exporting data container                      idi_tmp_
Giving myself all the names                   idi_tmp_
Using names                    data container=idi_tmp_-dee17767-a0c0-4680-a4fd-7a93073f9ff5
                            service container=idi_tmp_-dee17767-a0c0-4680-a4fd-7a93073f9ff5
Untarring package from container              /tmp/idi_tmp_258827863
Copying out of container                      idi_tmp_-dee17767-a0c0-4680-a4fd-7a93073f9ff5
                                         path=/home/eris/.eris/apps/idi
Move all files/dirs out of a dir and `rm -rf` that dir
                                         from=/tmp/idi_tmp_258827863/.eris
                                           to=/tmp/idi_tmp_258827863
No files to move
Removing directory                            /tmp/idi_tmp_258827863/.eris
Move all files/dirs out of a dir and `rm -rf` that dir
                                         from=/tmp/idi_tmp_258827863
                                           to=/home/mishravi/.eris/apps
Removing directory                            /tmp/idi_tmp_258827863
Package path does not exist on the host or is inside the pkg path
ABI path does not exist on the host or is inside the pkg path
EPM files do not exist on the host or are inside the pkg path
Removing data container                       idi_tmp_-dee17767-a0c0-4680-a4fd-7a93073f9ff5
Removing container                            idi_tmp_-dee17767-a0c0-4680-a4fd-7a93073f9ff5
Removing data dir on host                 dir=/home/mishravi/.eris/scratch/data/idi_tmp_

**Comment by compleatang** [comment]
No worries infi! When you run the command again just add the http in front of the compilers IP and it should kick in for you. If not let us know as we're happy to talk thru it with you.

**Comment by compleatang** [comment]
Sorry. Crossed messages. Did you update your service definition file to use the image "quay.io/eris/compilers:0.11.4"...?

**Comment by infinius12345** [comment]
Thank you for your prompt replies and kind words
Yes the i have updated ./eris/services/compilers but since i am using 0.12.0 i updated it to "quay.io/eris/compilers:0.11.4"

**Comment by compleatang** [comment]
OK. Great. Now run `eris services stop - rxf compilers && eris services start compilers` that will make sure the compilers take hold. Then retry the pkgs do command.

**Comment by infinius12345** [comment]
Thank You!! Finally i have been stuck on this for too long even though i got this error..
ABI Specification (From Compilers)            [{"constant":false,"inputs":[{"name":"x","type":"uint256"}],"name":"set","outputs":[],"type":"function"},{"constant":true,"inputs":[],"name":"get","outputs":[{"name":"retVal","type":"uint256"}],"type":"function"}]
Saving ABI                                    abi/IdisContractsFTW
Deploying Contract                       name=IdisContractsFTW
                                         code=606060405260978060106000396000f360606040526000357c01000000000000000000000000000000000000000000000000000000009004806360fe47b11460415780636d4ce63c14605757603f565b005b605560048080359060200190919050506078565b005b606260048050506086565b6040518082815260200191505060405180910390f35b806000600050819055505b50565b600060006000505490506094565b9056
                                       source=1475A062AE126DE72CFDE6B8CD6BE525EFC2340F
                                      chainID=simplechain
                                     chainURL=http://chain:46657/
                                      defAddr=1475A062AE126DE72CFDE6B8CD6BE525EFC2340F
                                       rawErr=timed out waiting for event
Error finalizing contract deploy idi.sol: 
There has been an error talking to your eris chain.

timed out waiting for event

Debugging this error is tricky, but don't worry the marmot recovery checklist is...
  * is the 1475A062AE126DE72CFDE6B8CD6BE525EFC2340F account right?
  * is the account you want to use in your keys service: eris keys ls ?
  * is the account you want to use in your genesis.json: eris chains cat simplechain genesis ?
  * is your chain making blocks: eris chains logs -f simplechain ?
  * do you have permissions to do what you're trying to do on the chain?

- I will try debugging this myself and if you want you can go ahead and close this ticket :)
Thank You so much again

**Comment by zramsay** [comment]
@infinius12345 what does your `epm.yaml` look like? Possibly try chainging `wait: true`to wait: false`

**Comment by zramsay** [comment]
also, to answer your initial questions about `eris update` ... `eris update branch=develop` though this we've had reports of a bug here. if you find that that _doesn't_ work. please comment on this issue: https://github.com/eris-ltd/eris-cli/issues/802

**Comment by compleatang** [comment]
closing. feel free to reopen if it isn't fixed.
