### ISSUE TITLE
Change dockerfile to utilize alpine base

### ISSUE THREAD

**Issue by compleatang** [eris-ltd/eris-compilers#79]
The docker image created here is massive and ubuntu based (for better or worse). We need to change this over to a smaller container with a better security profile and in line with the rest of our stack. Namely, we need to utilize alpine: build here as we do with eris-pm, eris-cm, keys, etc.

**Comment by AFDudley** [comment]
@VoR0220 you may want to consider doing this stuff as well:
https://github.com/eris-ltd/eris-db/blob/develop/Dockerfile#L54
