### ISSUE TITLE
`/healthz` endpoint

### ISSUE THREAD

**Issue by zramsay** [eris-ltd/eris-compilers#80]
**Problem:** Compilers are often down/not working which causes problems for several users (e.g. https://github.com/eris-ltd/eris-cli/issues/856)

**Solution:** A `/healthz` endpoint that run through some tests internally & ensures contracts can compile. This lets anyone "check that the compilers are up and will work" without having to send any contracts for compilation.

**Comment by SCBuergel** [comment]
Why not ship a compiler along with the eris binary and compile locally by default? This would prevent such issues in the first place and additionally be way more user-friendly in that I do not need to have internet connection to compile my contracts or setup a compiler myself.

**Comment by compleatang** [comment]
We're working in that direction. It should be done by 0.12.1 release. 0.12.0 official will have a `--local-compiler` flag that will manage everything. This issue is where we're working off of -> https://github.com/eris-ltd/eris-cli/issues/854

**Comment by compleatang** [comment]
Issue moved to [eris-ltd/eris-cli #996](https://github.com/eris-ltd/eris-cli/issues/996) via [**ZenHub**](https://www.zenhub.com/)
