### ISSUE TITLE
Need to enable versioning of solidity and soon

### ISSUE THREAD

**Issue by VoR0220** [eris-ltd/eris-compilers#90]
Problem: As can be seen here https://github.com/ethereum/solidity/blob/develop/Changelog.md there's a lot of breaking changes on the way in solidity. We need to get the compilers an ability to version. We also need to make sure that customers are getting something according to the version number for the PM so that we can begin tracking that. Pragmas have now been added that will generate a warning for all solidity files that do you specify a version requirement. This is both useful and a bit of a pain in the ass. 

Solution: We need to reconfigure the client to accept an object with any solidity specifiers that the user could want. We also need a way to effectively version, which currently doesn't exist for solidity except in the form of the solc-js .... this however means we will require some refactoring.

**Comment by compleatang** [comment]
closed by #96 update in dockerfile.
