### ISSUE TITLE
[Core] Better handle pragma warnings

### ISSUE THREAD

**Issue by VoR0220** [eris-ltd/eris-compilers#97]
Problem: Pragma warnings gives us an error that's essentially indecipherable. Need to better handle this.

Solution: This is going to be tricky because it's not in a neat JSON format. Might be worth the time to actually include the error in the combined-json output per a Solidity PR. Will have to talk it over and gauge what exactly we should do.

**Comment by compleatang** [comment]
Issue moved to [eris-ltd/eris-cli #997](https://github.com/eris-ltd/eris-cli/issues/997) via [**ZenHub**](https://www.zenhub.com/)
